---
- name: "Check for dhcpd executable file"
  ansible.builtin.stat:
    path: '/usr/sbin/dhcpd'
  changed_when: false
  register: dhcpd_binary

- name: "Install tasks"
  when: not dhcpd_binary.stat.exists
  block:
    - name: "Install requirement for ansible template"
      ansible.builtin.package:
        name: ["python-netaddr"]
        state: present

    - name: "Install isc-dhcp-server and requierements"
      ansible.builtin.package:
        name: ["isc-dhcp-server", "procps", "dhcpd-pools"]
        state: present

- name: "Configure defaults"
  ansible.builtin.template:
    src: "isc-dhcp-server.j2"
    dest: "/etc/default/isc-dhcp-server"
    mode: "0640"
  notify: Restart dhcpd

- name: "Configure config file"
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: "/etc/dhcp/dhcpd.conf"
    mode: "0640"
  notify: Restart dhcpd

- name: "Start and enable dhcpd"
  ansible.builtin.service:
    name: "isc-dhcp-server"
    state: started
    enabled: true
